# Generated by Django 4.2 on 2023-04-27 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webMercArticles', '0002_article_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='promoDebut',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de Début'),
        ),
        migrations.AddField(
            model_name='article',
            name='promoFin',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de Fin'),
        ),
        migrations.AddField(
            model_name='article',
            name='promoPourcent',
            field=models.IntegerField(default=0, verbose_name='En Pourcent'),
        ),
    ]
