# Generated by Django 4.2 on 2023-05-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webMercArticles', '0003_article_promodebut_article_promofin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='prixPromo',
            field=models.FloatField(default=0, verbose_name='Prix en Promo'),
        ),
    ]
