# Generated by Django 4.2 on 2023-05-06 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webMercArticles', '0004_article_prixpromo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='prixPromo',
        ),
    ]
