# Generated by Django 4.2 on 2023-05-07 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webMercArticles', '0005_remove_article_prixpromo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='photoArticle',
        ),
    ]
