# Generated by Django 4.2 on 2023-05-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webMercArticles', '0007_remove_article_categorie_article_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photoArticle',
            field=models.ImageField(default=None, upload_to='static'),
        ),
    ]
