# Generated by Django 4.2 on 2023-05-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webMercArticles', '0012_alter_article_photoarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photoArticle',
            field=models.ImageField(default=None, upload_to='photoArticle'),
        ),
    ]
