# Generated by Django 4.2 on 2023-05-19 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webMercArticles', '0013_alter_article_photoarticle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['categorie', 'dateCreation']},
        ),
        migrations.AddField(
            model_name='article',
            name='dateCreation',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
