# Generated by Django 4.2 on 2023-05-19 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webMercArticles', '0014_alter_article_options_article_datecreation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-dateCreation']},
        ),
    ]
