# Generated by Django 4.2 on 2023-05-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webMercArticles', '0015_alter_article_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='prix',
            field=models.FloatField(default=10),
        ),
    ]
