# Generated by Django 4.2 on 2023-05-20 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webMercArticles', '0016_alter_article_prix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ['-nomCateg']},
        ),
    ]
