# Generated by Django 4.2 on 2023-05-20 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webMercArticles', '0017_alter_categorie_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={},
        ),
    ]
